matrix:
  include:
    - language: java
      install: true
      jdk:
        - oraclejdk8
      script:
        - ./gradlew build

    - language: node_js
      node_js:
        - 10.15
      before_install:
        - cd Frontend
      install:
        - npm install
        - npm install --save axios
        - npm install --save bootstrap-vue
        - npm install --save jquery -D
        - npm install --save vue@2.6.10
        - npm install --save vue-template-compiler@2.6.10
        - npm install --save aos
        - npm install --save vue-cookie
        - npm install --save vue-router
      script:
        - npm run build

    - stage: deploy to backend app
      script: skip
      deploy:
        provider: heroku
        api_key: "18f21435-ea95-4281-b34a-000e79b86fee"
        app: cooperator-backend-3417

    - stage: deploy to frontend app
      script: skip
      deploy:
        provider: heroku
        api_key: "18f21435-ea95-4281-b34a-000e79b86fee"
        app: cooperator-frontend-3417